import 'package:equatable/equatable.dart';

import '../../shared/utils/dates.dart';
import 'budget.dart';
import 'json_parsing.dart';

/// `public.transaction_type`: the same enum budgets use (`expense|income`),
/// so a transaction and its budget compare by value.
typedef TransactionType = BudgetType;

/// A row of `api.v_transactions` (HU-17): an active income or expense of a
/// wallet the caller can read, with its budget and author.
///
/// Amounts in cents ([Cents]) like [Budget] and the wallet.
class Transaction extends Equatable {
  const Transaction({
    required this.transactionId,
    required this.walletId,
    required this.name,
    required this.type,
    required this.amountCents,
    required this.date,
    this.walletName,
    this.budgetId,
    this.budgetName,
    this.budgetIcon,
    this.userId,
    this.authorName,
    this.isScheduled = false,
    this.scheduledTransactionId,
    this.createdAt,
    this.updatedAt,
  });

  factory Transaction.fromJson(Map<String, dynamic> json) => Transaction(
    transactionId: (json['transaction_id'] as num).toInt(),
    walletId: (json['wallet_id'] as num).toInt(),
    walletName: json['wallet_name'] as String?,
    budgetId: (json['budget_id'] as num?)?.toInt(),
    budgetName: json['budget_name'] as String?,
    budgetIcon: BudgetIcon.parse(json['budget_icon']),
    userId: json['user_id'] as String?,
    authorName: json['author_name'] as String?,
    name: (json['name'] as String?) ?? '',
    type: TransactionType.parse(json['type']),
    amountCents: Cents.parse(json['amount']) ?? 0,
    date: json['date'] is String ? Dates.parseDay(json['date'] as String) : DateTime(1970),
    isScheduled: json['is_scheduled'] == true,
    scheduledTransactionId: (json['scheduled_transaction_id'] as num?)?.toInt(),
    createdAt: parseTimestamp(json['created_at']),
    updatedAt: parseTimestamp(json['updated_at']),
  );

  final int transactionId;
  final int walletId;
  final String? walletName;

  /// Null = «Sin presupuesto». The name and icon survive a later deletion of
  /// the budget (the view keeps them).
  final int? budgetId;
  final String? budgetName;
  final BudgetIcon? budgetIcon;

  /// Author. [authorName] may be a former member's name, «Usuario eliminado»
  /// or null (API 1.1).
  final String? userId;
  final String? authorName;

  final String name;
  final TransactionType type;
  final int amountCents;

  /// Business day in the author's zone (a plain `date`, never shifted).
  final DateTime date;

  /// Generated by a scheduled rule (F06).
  final bool isScheduled;
  final int? scheduledTransactionId;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  bool get isIncome => type == TransactionType.income;
  bool get hasBudget => budgetId != null;
  double get amount => Cents.toAmount(amountCents);

  /// HU-18/HU-19: the author or the wallet owner may edit or delete it. Only
  /// a UI hint: the API answers 404 to anyone else.
  bool canBeManagedBy(String? userId, {required bool walletIsOwner}) =>
      walletIsOwner || (userId != null && this.userId == userId);

  @override
  List<Object?> get props => [
    transactionId,
    walletId,
    walletName,
    budgetId,
    budgetName,
    budgetIcon,
    userId,
    authorName,
    name,
    type,
    amountCents,
    date,
    isScheduled,
    scheduledTransactionId,
    createdAt,
    updatedAt,
  ];
}

/// Position after the last row of a page, for keyset pagination over the
/// view's order `date.desc, transaction_id.desc`: rows inserted or deleted
/// meanwhile never shift or repeat the next page (unlike an offset).
class TransactionCursor extends Equatable {
  const TransactionCursor({required this.date, required this.transactionId});

  factory TransactionCursor.after(Transaction last) =>
      TransactionCursor(date: last.date, transactionId: last.transactionId);

  final DateTime date;
  final int transactionId;

  @override
  List<Object?> get props => [date, transactionId];
}

/// One page of `v_transactions` and where the next one starts (null at the end).
class TransactionPage extends Equatable {
  const TransactionPage(this.items, {this.next});

  final List<Transaction> items;
  final TransactionCursor? next;

  bool get hasMore => next != null;

  @override
  List<Object?> get props => [items, next];
}

/// What the transaction form sends to `create_transaction` /
/// `update_transaction`. The update replaces every field, so [toParams]
/// always sends all of them (a missing budget means «Sin presupuesto»).
class TransactionInput extends Equatable {
  const TransactionInput({
    required this.name,
    required this.type,
    required this.amountCents,
    required this.date,
    this.budgetId,
  });

  /// The form's current state for an existing transaction (edit mode).
  factory TransactionInput.fromTransaction(Transaction transaction) => TransactionInput(
    name: transaction.name,
    type: transaction.type,
    amountCents: transaction.amountCents,
    date: transaction.date,
    budgetId: transaction.budgetId,
  );

  final String name;
  final TransactionType type;
  final int amountCents;
  final DateTime date;
  final int? budgetId;

  Map<String, dynamic> toParams() => {
    'p_name': name.trim(),
    'p_type': type.apiValue,
    'p_amount': Cents.toAmount(amountCents),
    'p_date': Dates.toApi(date),
    'p_budget_id': budgetId,
  };

  @override
  List<Object?> get props => [name, type, amountCents, date, budgetId];
}
